In [1]:
import numpy as np
import pandas as pd
from utils import get_data_as_list
import re

In [2]:
data_list = get_data_as_list(day=6)
data_list[:15]

['2,1,1,1,1,1,1,5,1,1,1,1,5,1,1,3,5,1,1,3,1,1,3,1,4,4,4,5,1,1,1,3,1,3,1,1,2,2,1,1,1,5,1,1,1,5,2,5,1,1,2,1,3,3,5,1,1,4,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,4,1,5,1,2,1,1,1,1,5,1,1,1,1,1,5,1,1,1,4,5,1,1,3,4,1,1,1,3,5,1,1,1,2,1,1,4,1,4,1,2,1,1,2,1,5,1,1,1,5,1,2,2,1,1,1,5,1,2,3,1,1,1,5,3,2,1,1,3,1,1,3,1,3,1,1,1,5,1,1,1,1,1,1,1,3,1,1,1,1,3,1,1,4,1,1,3,2,1,2,1,1,2,2,1,2,1,1,1,4,1,2,4,1,1,4,4,1,1,1,1,1,4,1,1,1,2,1,1,2,1,5,1,1,1,1,1,5,1,3,1,1,2,3,4,4,1,1,1,3,2,4,4,1,1,3,5,1,1,1,1,4,1,1,1,1,1,5,3,1,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,1,1,1,1,1,1,1,1,5,1,4,4,1,1,1,1,1,1,1,1,3,1,3,1,4,1,1,2,2,2,1,1,2,1,1']

In [10]:
def get_array_data(data_list):
    list_of_strings = data_list[0].split(',')
    list_of_ints = [int(x) for x in list_of_strings]
    return list_of_ints

In [33]:
list_of_ints = get_array_data(data_list)

In [34]:
int_array = np.array(list_of_ints)

In [35]:
def lanternfish_after_1day(fish_age_array):
    fish_age_array = fish_age_array -1
    spawning_indices = np.where(fish_age_array < 0)[0]
    fish_age_array[spawning_indices] = 6
    fish_age_array = np.append(fish_age_array, len(spawning_indices) * [8])
    return fish_age_array

In [36]:
n_days = 80
while n_days > 0:
    int_array = lanternfish_after_1day(int_array)
    n_days -= 1

In [37]:
len(int_array)

388739

# test data

In [26]:
test_ints = np.array([3,4,3,1,2])

In [27]:
n_days = 80
while n_days > 0:
    test_ints = lanternfish_after_1day(test_ints)
    print(test_ints)
    n_days -= 1

[2. 3. 2. 0. 1.]
[1. 2. 1. 6. 0. 8.]
[0. 1. 0. 5. 6. 7. 8.]
[6. 0. 6. 4. 5. 6. 7. 8. 8.]
[5. 6. 5. 3. 4. 5. 6. 7. 7. 8.]
[4. 5. 4. 2. 3. 4. 5. 6. 6. 7.]
[3. 4. 3. 1. 2. 3. 4. 5. 5. 6.]
[2. 3. 2. 0. 1. 2. 3. 4. 4. 5.]
[1. 2. 1. 6. 0. 1. 2. 3. 3. 4. 8.]
[0. 1. 0. 5. 6. 0. 1. 2. 2. 3. 7. 8.]
[6. 0. 6. 4. 5. 6. 0. 1. 1. 2. 6. 7. 8. 8. 8.]
[5. 6. 5. 3. 4. 5. 6. 0. 0. 1. 5. 6. 7. 7. 7. 8. 8.]
[4. 5. 4. 2. 3. 4. 5. 6. 6. 0. 4. 5. 6. 6. 6. 7. 7. 8. 8.]
[3. 4. 3. 1. 2. 3. 4. 5. 5. 6. 3. 4. 5. 5. 5. 6. 6. 7. 7. 8.]
[2. 3. 2. 0. 1. 2. 3. 4. 4. 5. 2. 3. 4. 4. 4. 5. 5. 6. 6. 7.]
[1. 2. 1. 6. 0. 1. 2. 3. 3. 4. 1. 2. 3. 3. 3. 4. 4. 5. 5. 6. 8.]
[0. 1. 0. 5. 6. 0. 1. 2. 2. 3. 0. 1. 2. 2. 2. 3. 3. 4. 4. 5. 7. 8.]
[6. 0. 6. 4. 5. 6. 0. 1. 1. 2. 6. 0. 1. 1. 1. 2. 2. 3. 3. 4. 6. 7. 8. 8.
 8. 8.]
[5. 6. 5. 3. 4. 5. 6. 0. 0. 1. 5. 6. 0. 0. 0. 1. 1. 2. 2. 3. 5. 6. 7. 7.
 7. 7. 8. 8. 8.]
[4. 5. 4. 2. 3. 4. 5. 6. 6. 0. 4. 5. 6. 6. 6. 0. 0. 1. 1. 2. 4. 5. 6. 6.
 6. 6. 7. 7. 7. 8. 8. 8. 8. 8.]
[3. 4. 3. 1. 2. 3.

 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[1. 2. 1. 6. 0. 1. 2. 3. 3. 4. 1. 2. 3. 3. 3. 4. 4. 5. 5. 6. 1. 2. 3. 3.
 3. 3. 4. 4. 4. 5. 5. 5. 5. 5. 6. 6. 6. 0. 0. 1. 1. 2. 3. 3. 3. 3. 3. 4.
 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 5. 5. 5.
 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4.
 4. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.
 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 7. 7. 7. 7. 7. 7.
 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7. 7.
 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[0. 1. 0. 5. 6. 0. 1. 2. 2. 3. 0. 1. 2. 2. 2. 3. 3. 4. 4. 5. 0. 1. 2. 2.
 2. 2. 3. 3. 3. 4. 4. 4. 4. 4. 5. 5. 5. 6. 6. 0. 0. 1. 2. 

 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[0. 1. 0. 5. 6. 0. 1. 2. 2. 3. 0. 1. 2. 2. 2. 3. 3. 4. 4. 5. 0. 1. 2. 2.
 2. 2. 3. 3. 3. 4. 4. 4. 4. 4. 5. 5. 5. 6. 6. 0. 0. 1. 2. 2. 2. 2. 2. 3.
 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6.
 6. 0. 0. 0. 0. 0. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3.
 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3.
 3. 

 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
[2. 3. 2. 0. 1. 2. 3. 4. 4. 5. 2. 3. 4. 4. 4. 5. 5. 6. 6. 0. 2. 3. 4. 4.
 4. 4. 5. 5. 5. 6. 6. 6. 6. 6. 0. 0. 0. 1. 1. 2. 2. 3. 4. 4. 4. 4. 4. 5.
 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.
 1. 2. 2. 2. 2. 2. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 5. 5. 5. 5. 5. 6. 6. 6.
 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5.
 5. 5. 5. 5. 5. 5. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6. 6.
 6. 6. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 5. 5.
 

[6. 0. 6. ... 8. 8. 8.]
[5. 6. 5. ... 8. 8. 8.]
[4. 5. 4. ... 8. 8. 8.]
[3. 4. 3. ... 8. 8. 8.]
[2. 3. 2. ... 8. 8. 8.]
[1. 2. 1. ... 8. 8. 8.]
[0. 1. 0. ... 8. 8. 8.]
[6. 0. 6. ... 8. 8. 8.]
[5. 6. 5. ... 8. 8. 8.]
[4. 5. 4. ... 8. 8. 8.]
[3. 4. 3. ... 8. 8. 8.]
[2. 3. 2. ... 8. 8. 8.]
[1. 2. 1. ... 8. 8. 8.]
[0. 1. 0. ... 8. 8. 8.]


In [28]:
len(test_ints)

5934

# second part


when trying the same way, I run out of memory. not quite surprising... the pandemic has taught us, that exponentil growth is pretty crazy, right?  
after consulting some reddit posts, it seems grouping the fish is the way to go

In [104]:
int_array = np.array(list_of_ints)

In [110]:
# build my initial count of fish as numpy array
count = np.empty(9)
for ind in np.arange(9):
    count[ind] = np.count_nonzero(int_array == ind)
count

array([  0., 200.,  27.,  25.,  23.,  25.,   0.,   0.,   0.])

In [111]:
def grouped_fish_after_1day(count):
    # how many will be spawning today
    spawning = count[0]
    # all get one day closer to spawning
    count[0:8] = count[1:9]
    # add new ones
    count[8] = spawning
    # keep the old ones in as well
    count[6] += spawning
    return count

In [112]:
n_days = 256
while n_days > 0:
    count = grouped_fish_after_1day(count)
    n_days -= 1

In [113]:
solution2 = count.sum()
solution2

1741362314973.0